//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 剧享网.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AgreeDisagree
    {
        public int A_Id { get; set; }
        public int U_Id { get; set; }
        public int W_Id { get; set; }
        public int A_InfoId { get; set; }
        public int A_AgreeCount { get; set; }
        public int A_DisAgreeCount { get; set; }
    }
}
