//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 剧享网.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Comment
    {
        public string U_UserName { get; set; }
        public int U_Id { get; set; }
        public int C_Id { get; set; }
        public string C_UserName { get; set; }
        public int W_Id { get; set; }
        public string C_WorkName { get; set; }
        public string C_WorkTime { get; set; }
        public int C_InfoId { get; set; }
        public string C_Info { get; set; }
        public int C_Response { get; set; }
        public string C_CommentTime { get; set; }
    }
}
