//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 剧享网.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_IpReport
    {
        public int I_Id { get; set; }
        public string I_Ipv4 { get; set; }
        public int C_TypeId { get; set; }
        public Nullable<System.DateTime> I_EnTime { get; set; }
        public Nullable<System.DateTime> I_QuitTime { get; set; }
    }
}
