//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 剧享网.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_NotifyInfoRecord
    {
        public int N_Id { get; set; }
        public string U_UserName { get; set; }
        public string N_Content { get; set; }
        public Nullable<System.DateTime> N_Time { get; set; }
    }
}
