//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 剧享网.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_NotifyInfo
    {
        public int N_Id { get; set; }
        public string N_ReplyUserName { get; set; }
        public string N_ReplyObject { get; set; }
        public int W_Id { get; set; }
        public string N_WorkName { get; set; }
        public string N_Time { get; set; }
        public string N_SystemContent { get; set; }
        public int N_ReadStatus { get; set; }
    }
}
