//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 剧享网.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public int U_Id { get; set; }
        public string R_Id { get; set; }
        public string U_HeadImgPath { get; set; }
        public string U_UserName { get; set; }
        public string U_UserPassWord { get; set; }
        public string U_Email { get; set; }
        public string U_UserTelNum { get; set; }
        public int U_RoleIsOpen { get; set; }
        public int U_SendSpace { get; set; }
        public Nullable<System.DateTime> U_RegisterTime { get; set; }
    }
}
